(() => {
'use strict';
const $=id=>document.getElementById(id),read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let mode='login',currentUser=null,activeChannel='general';
const channelData={general:'Welcome to Moon Chat','off-topic':'Talk about anything',gaming:'Games, clips, and squads',help:'Ask the community'};
const show=id=>{document.querySelectorAll('.form-step').forEach(x=>x.classList.remove('active'));$(id)?.classList.add('active')};
const status=t=>{if($('form-status'))$('form-status').textContent=t||''};
const profileImage=(img,url)=>{if(url){img.src=url;img.classList.remove('hidden');img.onerror=()=>img.classList.add('hidden')}else img.classList.add('hidden')};
// Lightweight background
const canvas=$('bg-canvas'),ctx=canvas.getContext('2d'),mouse={x:-999,y:-999};let dots=[];
function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);dots=Array.from({length:Math.min(130,Math.max(55,innerWidth*innerHeight/16000))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.25,vy:(Math.random()-.5)*.25,r:Math.random()*1.4+.6}))}
function animate(){ctx.clearRect(0,0,innerWidth,innerHeight);dots.forEach(p=>{const x=mouse.x-p.x,y=mouse.y-p.y,d=Math.hypot(x,y);if(d>0&&d<170){const f=(170-d)/170;p.x+=x/d*f*.6;p.y+=y/d*f*.6}p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>innerWidth)p.vx*=-1;if(p.y<0||p.y>innerHeight)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill()});requestAnimationFrame(animate)}
addEventListener('resize',resize);addEventListener('mousemove',e=>{mouse.x=e.clientX;mouse.y=e.clientY;if(!$('card-container').matches(':hover'))$('glass-card').style.transform=`rotateX(${-(e.clientY/innerHeight-.5)*12}deg) rotateY(${(e.clientX/innerWidth-.5)*12}deg)`},{passive:true});$('card-container').onmouseenter=()=>$('glass-card').style.transform='rotateX(0) rotateY(0)';resize();animate();
function setMode(m){mode=m;$('toggle-login').classList.toggle('active',m==='login');$('toggle-signup').classList.toggle('active',m==='signup');$('auth-title').textContent=m==='login'?'Welcome back':'Create an account';$('submit-btn').textContent=m==='login'?'Login':'Create account';$('birthdate-group').classList.toggle('hidden',m!=='signup');$('birthdate').required=m==='signup';status('')}
$('toggle-login').onclick=()=>setMode('login');$('toggle-signup').onclick=()=>setMode('signup');
$('auth-form').onsubmit=e=>{e.preventDefault();const name=$('username').value.trim(),pass=$('password').value,key=name.toLowerCase();if(!name||pass.length<4||(mode==='signup'&&!$('birthdate').value)){status('Complete the required fields.');return}const accounts=read('moon-chat-accounts',{});if(mode==='signup'){if(accounts[key]){status('That username is already taken.');return}currentUser={username:name,password:pass,role:key==='steezy'?'owner':'member',banned:false,mutedUntil:0,picture:''};accounts[key]=currentUser;write('moon-chat-accounts',accounts);$('username-preview').textContent=name;show('customize-section')}else{currentUser=accounts[key];if(!currentUser||currentUser.password!==pass){status('Incorrect username or password.');return}if(currentUser.banned){status('This account is banned.');return}if(key==='steezy')currentUser.role='owner';enterChat()}};
function updatePreview(){const p=$('username-preview'),c=$('font-color').value;p.style.fontFamily=$('font-family').value;p.style.color=c;p.style.textShadow=$('glow-toggle').checked?`0 0 14px ${c}`:'none';profileImage($('profile-preview-image'),$('profile-picture').value.trim())}
['font-family','font-color','glow-toggle','profile-picture'].forEach(id=>$(id).addEventListener('input',updatePreview));$('save-profile-btn').onclick=()=>{if(!currentUser)return;currentUser.picture=$('profile-picture').value.trim();currentUser.font=$('font-family').value;currentUser.color=$('font-color').value;currentUser.glow=$('glow-toggle').checked;const a=read('moon-chat-accounts',{});a[currentUser.username.toLowerCase()]=currentUser;write('moon-chat-accounts',a);enterChat()};
function messageKey(){return`moon-chat-messages-${activeChannel}`};
function renderMessage(m){const b=document.createElement('article');b.className='msg-block';const h=document.createElement('div');h.className='msg-head';const author=document.createElement('b');author.textContent=m.username;const time=document.createElement('time');time.className='msg-time';time.textContent=m.time||'';h.append(author,time);const text=document.createElement('p');text.textContent=m.content;b.append(h,text);const account=read('moon-chat-accounts',{})[m.username.toLowerCase()];if(account?.font){text.style.fontFamily=account.font}if(account?.color){text.style.color=account.color}if(account?.glow){text.style.textShadow=`0 0 10px ${account.color||'#fff'}`}if(currentUser?.role==='owner'&&m.username.toLowerCase()!=='steezy'){const tools=document.createElement('div');tools.className='mod-tools';[['timeout','Timeout'],['mute','Mute'],['ban','Ban']].forEach(([a,l])=>{const x=document.createElement('button');x.type='button';x.textContent=l;x.onclick=()=>moderate(a,m.username);tools.append(x)});b.append(tools)}$('message-container').append(b)}
function loadMessages(){$('message-container').replaceChildren();read(messageKey(),[]).forEach(renderMessage)}
function renderChannels(){const list=$('channel-list');list.replaceChildren();Object.keys(channelData).forEach(id=>{const b=document.createElement('button');b.type='button';b.className=`channel-btn${id===activeChannel?' active':''}`;b.textContent=`#  ${id}`;b.onclick=()=>selectChannel(id);list.append(b)})}
function selectChannel(id){activeChannel=id;$('room-title').textContent=`# ${id}`;$('channel-topic').textContent=channelData[id];$('chat-msg').placeholder=`Message # ${id}`;renderChannels();loadMessages()}
function enterChat(){if(!currentUser)return;$('sidebar-username').textContent=currentUser.username;$('sidebar-role').textContent=currentUser.role==='owner'?'Owner':'Member';$('user-avatar').textContent=currentUser.username[0].toUpperCase();profileImage($('user-avatar-image'),currentUser.picture);$('user-role-badge').textContent=currentUser.role.toUpperCase();$('card-container').style.maxWidth='1080px';show('chat-section');selectChannel(activeChannel);$('chat-msg').focus()}
function moderate(action,target){if(currentUser?.role!=='owner')return;const a=read('moon-chat-accounts',{}),k=target.toLowerCase();if(!a[k])return;if(action==='ban')a[k].banned=true;if(action==='mute')a[k].mutedUntil=Date.now()+365*86400000;if(action==='timeout')a[k].mutedUntil=Date.now()+600000;write('moon-chat-accounts',a);loadMessages()}
$('chat-input-form').onsubmit=e=>{e.preventDefault();const i=$('chat-msg'),content=i.value.trim(),a=read('moon-chat-accounts',{})[currentUser.username.toLowerCase()];if(!content||a?.mutedUntil>Date.now())return;const m={username:currentUser.username,content,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};const ms=read(messageKey(),[]);ms.push(m);write(messageKey(),ms.slice(-100));renderMessage(m);i.value='';i.focus()};
function openSettings(){const a=currentUser||{};$('settings-display-name').value=a.username||'';$('settings-picture').value=a.picture||'';$('settings-font').value=a.font||'Segoe UI, sans-serif';$('settings-color').value=a.color||'#ffffff';$('settings-glow').checked=!!a.glow;$('settings-panel').classList.remove('hidden')}
$('settings-btn').onclick=openSettings;$('close-settings').onclick=()=>$('settings-panel').classList.add('hidden');$('save-settings').onclick=()=>{if(!currentUser)return;const name=$('settings-display-name').value.trim()||currentUser.username,key=currentUser.username.toLowerCase(),a=read('moon-chat-accounts',{});currentUser.username=name;currentUser.picture=$('settings-picture').value.trim();currentUser.font=$('settings-font').value;currentUser.color=$('settings-color').value;currentUser.glow=$('settings-glow').checked;delete a[key];a[name.toLowerCase()]=currentUser;write('moon-chat-accounts',a);$('settings-status').textContent='Settings saved';enterChat();setTimeout(()=>$('settings-panel').classList.add('hidden'),500)};
setMode('login');
})();
